# Generated by Django 3.0.1 on 2019-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('post_text', models.CharField(max_length=500, verbose_name='Текст поста')),
                ('pub_data', models.DateTimeField(verbose_name='Дата публикации')),
                ('post_image', models.URLField(max_length=255, verbose_name='Изображение')),
            ],
        ),
    ]
